const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('timerAPI', {
  start: (ms) => ipcRenderer.invoke('timer:start', ms),
  pause: () => ipcRenderer.invoke('timer:pause'),
  reset: () => ipcRenderer.invoke('timer:reset'),
  resume: () => ipcRenderer.invoke('timer:resume'),
  seek: (ms) => ipcRenderer.invoke('timer:seek', ms),
  setTitle: (title) => ipcRenderer.invoke("timer:setTitle", title),
  onTitle: (cb) => ipcRenderer.on("timer:title", (_e, data) => cb(data)),
  getState: () => ipcRenderer.invoke('timer:getState'),
  onUpdate: (cb) => ipcRenderer.on('timer:update', (_e, data) => cb(data)),
  onFinished: (cb) => ipcRenderer.on('timer:finished', (_e, data) => cb(data)),
  savePreset: (preset) => ipcRenderer.invoke("timer:savePreset", preset),
  deletePreset: (id) => ipcRenderer.invoke("timer:deletePreset", id),
  saveSettings: (settings) => ipcRenderer.invoke("timer:saveSettings", settings),
  setNotes: (notes) => ipcRenderer.invoke("timer:setNotes", notes),
  onConfigUpdate: (cb) => ipcRenderer.on("timer:configUpdate", (_e, data) => cb(data)),
  onNotes: (cb) => ipcRenderer.on("timer:notes", (_e, data) => cb(data)),
  onServerInfo: (cb) => ipcRenderer.on('server:info', (_e, data) => cb(data)),
  startTunnel: () => ipcRenderer.invoke('timer:startTunnel'),
  stopTunnel: () => ipcRenderer.invoke('timer:stopTunnel'),
  blockDevice: (socketId, deviceId) => ipcRenderer.invoke('timer:blockDevice', { socketId, deviceId }),
  unblockDevice: (deviceId) => ipcRenderer.invoke('timer:unblockDevice', deviceId),
  onDevicesUpdate: (cb) => ipcRenderer.on('timer:devicesUpdate', (_e, data) => cb(data)),
  getDevices: () => ipcRenderer.invoke('timer:getDevices'),
  refreshPin: () => ipcRenderer.invoke('timer:refreshPin'),
  flash: () => ipcRenderer.invoke('timer:flash'),
  onFlash: (cb) => ipcRenderer.on('timer:flash', () => cb()),
  onProjectorStatus: (cb) => ipcRenderer.on('timer:projectorStatus', (_e, data) => cb(data)),
  controlProjector: (action, data) => ipcRenderer.invoke('timer:controlProjector', action, data)
});
